name: odyssey
description: A personal goal tracking app with stages and repeating subgoals.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  google_sign_in: ^7.2.0
  flutter_svg: ^2.0.9
  provider: ^6.1.2
  intl: ^0.20.2
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/odyssey_logo.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/odyssey_logo_orange.png"
  remove_alpha_ios: true
