// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgaTxlnSydqTfXlFwji_3_CZWys6_ERfY',
    appId: '1:352109049226:web:f62477f4b60599adb28473',
    messagingSenderId: '352109049226',
    projectId: 'odyssey-4600e',
    authDomain: 'odyssey-4600e.firebaseapp.com',
    storageBucket: 'odyssey-4600e.firebasestorage.app',
    measurementId: 'G-MLY9FGL5ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcZdSHXRHUc-CeNg1RVpOrq_TNrzA1wo',
    appId: '1:352109049226:android:cd7d36c995161333b28473',
    messagingSenderId: '352109049226',
    projectId: 'odyssey-4600e',
    storageBucket: 'odyssey-4600e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWNLO_JOUQtDmGHUZRGFLHK46e1rMEK6M',
    appId: '1:352109049226:ios:dba4721af666429cb28473',
    messagingSenderId: '352109049226',
    projectId: 'odyssey-4600e',
    storageBucket: 'odyssey-4600e.firebasestorage.app',
    androidClientId: '352109049226-r1t8lhr8p3qmns6if0rpkct490hk9o1q.apps.googleusercontent.com',
    iosClientId: '352109049226-ulp5rg98ql143phillf42lho1mq368sb.apps.googleusercontent.com',
    iosBundleId: 'com.jakefogel.odyssey',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWNLO_JOUQtDmGHUZRGFLHK46e1rMEK6M',
    appId: '1:352109049226:ios:c432ae857310e0e5b28473',
    messagingSenderId: '352109049226',
    projectId: 'odyssey-4600e',
    storageBucket: 'odyssey-4600e.firebasestorage.app',
    androidClientId: '352109049226-r1t8lhr8p3qmns6if0rpkct490hk9o1q.apps.googleusercontent.com',
    iosClientId: '352109049226-s56mo9rj6ebl6ut9mtnf0avuaedelsbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.odyssey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgaTxlnSydqTfXlFwji_3_CZWys6_ERfY',
    appId: '1:352109049226:web:1ff0072ac8eaa4bcb28473',
    messagingSenderId: '352109049226',
    projectId: 'odyssey-4600e',
    authDomain: 'odyssey-4600e.firebaseapp.com',
    storageBucket: 'odyssey-4600e.firebasestorage.app',
    measurementId: 'G-YKRSW7GS34',
  );
}
